# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.24

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.24.1/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.24.1/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/kylefahey/CLionProjects/c876_cpp23

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/kylefahey/CLionProjects/c876_cpp23

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.24.1/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.24.1/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/kylefahey/CLionProjects/c876_cpp23/CMakeFiles /Users/kylefahey/CLionProjects/c876_cpp23//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/kylefahey/CLionProjects/c876_cpp23/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named c876_cpp23

# Build rule for target.
c876_cpp23: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 c876_cpp23
.PHONY : c876_cpp23

# fast build rule for target.
c876_cpp23/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c876_cpp23.dir/build.make CMakeFiles/c876_cpp23.dir/build
.PHONY : c876_cpp23/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c876_cpp23.dir/build.make CMakeFiles/c876_cpp23.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c876_cpp23.dir/build.make CMakeFiles/c876_cpp23.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c876_cpp23.dir/build.make CMakeFiles/c876_cpp23.dir/main.cpp.s
.PHONY : main.cpp.s

roster.o: roster.cpp.o
.PHONY : roster.o

# target to build an object file
roster.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c876_cpp23.dir/build.make CMakeFiles/c876_cpp23.dir/roster.cpp.o
.PHONY : roster.cpp.o

roster.i: roster.cpp.i
.PHONY : roster.i

# target to preprocess a source file
roster.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c876_cpp23.dir/build.make CMakeFiles/c876_cpp23.dir/roster.cpp.i
.PHONY : roster.cpp.i

roster.s: roster.cpp.s
.PHONY : roster.s

# target to generate assembly for a file
roster.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c876_cpp23.dir/build.make CMakeFiles/c876_cpp23.dir/roster.cpp.s
.PHONY : roster.cpp.s

student.o: student.cpp.o
.PHONY : student.o

# target to build an object file
student.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c876_cpp23.dir/build.make CMakeFiles/c876_cpp23.dir/student.cpp.o
.PHONY : student.cpp.o

student.i: student.cpp.i
.PHONY : student.i

# target to preprocess a source file
student.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c876_cpp23.dir/build.make CMakeFiles/c876_cpp23.dir/student.cpp.i
.PHONY : student.cpp.i

student.s: student.cpp.s
.PHONY : student.s

# target to generate assembly for a file
student.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c876_cpp23.dir/build.make CMakeFiles/c876_cpp23.dir/student.cpp.s
.PHONY : student.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... c876_cpp23"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... roster.o"
	@echo "... roster.i"
	@echo "... roster.s"
	@echo "... student.o"
	@echo "... student.i"
	@echo "... student.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

